const all_events = [
    {
        "title": "Guess The Tune",
        "days": ["2"],
        "tagline": "Western battle of bands!",
        "desc": "Effervescence’s coveted inter-college Battle of Bands, Pulse attracts talent from all over the country and showcases the best music you may have yet heard.",
        "link": "https://docs.google.com/document/d/1I6YPyxz2CEEzXJRHBcOGzQiPIfFvYg9uAQa4d16oTU0/edit?usp=sharing",
        "location": "SAC (Students Activity Center)",
        "date_time": "4th March 2022, 9:00 AM Onwards",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/tune.png?raw=true",
        "type": "Music_Dance",
    },
    {
        "title": "Impulso",
        "days": ["3"],
        "tagline": "Semi-professional Eastern and Contemporary group dance",
        "desc": "Effervescence '22 brings to you the much awaited classical extravaganza Tandav, a team event, where some of the most talented artistes battle it out with prizes worth 30K up for grabs!",
        "link": "https://docs.google.com/document/d/1bplbnNvUfBglps2ft5KHoTqheOsvqyNV7O6KkB6NwDo/edit?usp=sharing",
        "location": "SJA, IIITA",
        "date_time": "5th March 2022, 9:00 AM Onwards",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/impulso.png?raw=true",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/creative-cultural-event/tandav-Effervescence-2022-national-institute-of-technology-karnataka-IIITA-surathkal-269172"
    },
    {
        "title": "Euphony",
        "days": ["3"],
        "tagline": "Semi-professional Eastern and Contemporary solo dance",
        "desc": "Effervescence '22 brings to you Nritya, the Classical Eastern and Contemporary Solo Dance Competition where the best dancers across the country morph the diverse ethnic Indian Dance forms into unforgettable performances with prizes upto 13K up for the taking.",
        "link": "https://docs.google.com/document/d/1A1JPlI9aziwBWdQDsrjIZiZkzJ6SbHmNz5Xep-T4Cu8/edit?usp=sharing",
        "location": "SJA, IIITA",
        "date_time": "5th March 2022, 12:00 PM onwards",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/euphony.png?raw=true",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/creative-cultural-event/nrithya-Effervescence-2022-national-institute-of-technology-karnataka-IIITA-surathkal-269225"
    },
    {
        "title": "Antakshari",
        "days": ["3"],
        "tagline": "Elevate Your Dance.",
        "desc": "Dance Workshop is a warm and inviting space for youth to enjoy and learn the art of dance.",
        "link": "https://docs.google.com/document/d/1BaoALbjW2NhpbDThiBBGoNhH7S8MKNgfDytsN2ITmJs/edit",
        "location": "Seminar Hall, Mechanical Dept, IIITA",
        "date_time": "5th March 2022, 9:00 AM onwards",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/antakshari.png?raw=true",
        "type": "Music_Dance",
        "registration_link": "https://dare2compete.com/workshop/dance-workshop-Effervescence-2022-national-institute-of-technology-karnataka-IIITA-surathkal-269232"
    },
    {
        "title": "Euphony4",
        "days": ["2"],
        "tagline": "Pure, raw, strong and moving",
        "desc": "Pure, raw, strong and moving. Effervescence 2022 Musicals brings to you, Raaga-Rhapsody, the solo vocals competition. From Ballads to Alaaps, this event gives you a stage to wow us with your singing and a chance to win the title of “Voice of Effe”.",
        "link": "https://docs.google.com/document/d/1CnDneReEvqK483zO2Aa4G4fLZ4E1euT9c4Vu6o-z_tI/edit?usp=sharing",
        "location": "SAC (Students Activity Center)",
        "date_time": "4th March 2022, 1:30 PM Onwards",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/impulso.png?raw=true",
        "type": "Music_Dance",
    },



    {
        "title": "Euphony5",
        "days": ["3"],
        "tagline": "Attentinon all foodies!🍔🤤 The Realm shall put your gluttony to the test at the Hogathon 2022. ",
        "desc": "Join the others in this epic competition where the one who shall chow down on the food in the least time shall be crowned the victor!",
        "location": "Chem Block Road",
        "date_time": "12PM-2PM",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/quiz.png?raw=true",
        "type": "Specials"
    },
    {
        "title": "Euphony6",
        "days": ["4"],
        "tagline": "Adventure Time!",
        "desc": "Got the hots for the thrills of adventure? We present to you the <b>Adventure Zone</b>, so that the junta gets the full Effervescence Experience™️. With games such as: <br/><br/> <b>Mechanical Bull: </b> Can you last 8 seconds? 😏 On the bucking animatronic bull, we mean. We will put your rodeo skills to the test here. <br/><br/> <b>Slippery Soccer:</b> it's slippy football, what more do you need? Come with your friends to have a jolly time sliding around, playing the most popular sport in the world. <br/><br/><b>Archery:</b> If you had the urge to test your archery skills when the Olympics were on, thinking that hmmmm I could do this, boy do we have an opportunity for you!<br/><br/><b>Bubble Ball:</b> Don the big bubble and go wild. Ram into your friends like a truck and get ragdolled yourself! It's anybody's game!<br/><br/><b>Sumo Wrestling:</b> Sumo. Wrestling. Wear comically oversized sumo outfits and defeat your friends in the way of the Rikishi!",
        "location": "Old Chemical Dept Road, near Suprabha",
        "date_time": "10AM-5PM",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/quiz.png?raw=true",
        "type": "Specials"
    },
    {
        "title": "Euphony7",
        "days": ["2", "3", "4"],
        "tagline": "Come for the Kadak Chai, stay for the Kadak Artistry",
        "desc": "ChaiPoint is our effort at discovering and supporting local talent. Be it stand up or poetry, instrumental or vocational, our stage is open for all. While the patrons relish a steaming cup of chai, the artists get to exhibit their forte. If you’re a budding artiste holding back for the right opportunity or someone who just wants to kickback and enjoy a pleasant evening, ChaiPoint is the venue for you.",
        "location": "New Chemical Building ",
        "date_time": "4PM-8PM",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/tune.png?raw=true",
        "type": "Specials",
        "link": "https://docs.google.com/document/d/1On_pzgcVUGO1ucN6DqyWvsXkzd54qhuI4yV1vqVeFJg/edit?usp=sharing",
    },
    {
        "title": "Sketchers",
        "days": ["2"],
        "tagline": "we are not led, we lead",
        "desc": "The Best Management Team is that golden ticket to showcase your talents, creativity and abilities in terms of 5 M's of management which will help you to gain knowledge and improvise your expertise.",
        "link": "https://docs.google.com/document/d/1oEE_iq6ioDohnGAy_T-D3vXNH5CqVdUnVU9YV77EwKU/edit?usp=sharing",
        "location": "LHC-C, IIITA",
        "date_time": "26th February 12:00 AM to 4th March 11:59 PM",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/skechers.png?raw=true",
        "type": "Biz",
    },
    {
        "title": "Chess",
        "days": ["2"],
        "tagline": " A Realm Of Marketing",
        "desc": "Always sharing memes and decoding the latest trending ads? Well, why not win some prizes while you're at it!",
        "link": "https://docs.google.com/document/d/17CoOiwDDL1M6hT5BYrl9OulbSxBiLo4P3Ud5j9bqw4Y/edit?usp=sharing",
        "location": "Online",
        "date_time": "26th February 12:00 AM to 4th March 11:59 PM",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/chess.png?raw=true",
        "type": "Biz",
    },
    {
        "title": "Euphony 7",
        "days": ["4"],
        "tagline": "Pitching meets Pop Culture!",
        "desc": "A first-of-its-kind event that combines business acumen with pop culture!",
        "link": "https://docs.google.com/document/d/1Wz8MfwpQzzYvZUwm2e_PktDwOumSF4FBtsYjh8NxAXw/edit?usp=sharing",
        "location": "Online",
        "date_time": "6th March 2022, 10:00 AM Onwards",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/quiz.png?raw=true",
        "type": "Biz",
    },
    {
        "title": "Euphony8",
        "days": ["3"],
        "tagline": "No risk and no loss, the only case opportunity you will come across.",
        "desc": "Effervescence IIITA in association with E-Cell IIITA invites you to “Case Crunch”, an extreme Case Study competition, which will bring out some of the best ideas in your mind and challenge your entrepreneurial spirit. Dive into the sea of opportunities that is Case Crunch and stand a chance to win prizes worth 20k!",
        "link": "https://docs.google.com/document/d/1MDTtTXMKgvktMtYFw25-sPgQgeTmVcXqsAwMyHGRFBU/edit?usp=sharing",
        "location": "Online and Offline for final",
        "date_time": "5th March 2022, 9:00 AM - 5:00 PM",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/feathers.png?raw=true",
        "type": "Biz",
        "registration_link": ""
    },
    {
        "title": "Euphony9",
        "days": ["2"],
        "tagline": "Put on your shining armour and test your crypto mettle",
        "desc": "BizEvents from Team Effervescence aims to get students familiarised and exposed to the cryptocurrency market with real-world trading without actually investing their own money.",
        "link": "https://docs.google.com/document/d/1Y_AC4eBmf_C9Zu4xTu00p_l81AhoTeB8hM5ih-7GzYc/edit?usp=sharing",
        "location": "Online",
        "date_time": "26th February 12:00 AM to 4th March 11:59 PM",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/consilio.png?raw=true",
        "type": "Biz",
        "registration_link": ""
    },


    {
        "title": "Euphony10",
        "days": ["3"],
        "tagline": "",
        "desc": "This contest aims at giving a stage where all are allowed to compete and voice their thoughts and the winner will be crowned as the TSAR. ",
        "link": "https://docs.google.com/document/d/10yhClWp2u9YxQa7bCQMDlHvgtXU3cw8oJEV_6ezVePM/edit?usp=sharing",
        "location": "SOM Seminar Hall",
        "date_time": "5th March 2022, 1PM - 3PM",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/tune.png?raw=true",
        "type": "Lit",
        "registration_link": ""
    },
    {
        "title": "Quiz2",
        "days": ["4"],
        "tagline": "The wind is rising",
        "desc": "Tired of annoying online zoom quizzes? Missed the thrill of quizzing the way it was always meant to be, that is, in person ?\nHow would you like not 1 or 2, but a collection of 7 exciting quizzes?\nLSD Quizsoc presents, Askerville Manor, a week-long quiz fest with a wide variety of topics",
        "link": "https://docs.google.com/document/d/1-3Er3fIsE2weMjK7gHgZqn40-EOAlWkEggHgHcD4TuU/edit?usp=sharing",
        "location": "Main Seminar Hall",
        "date_time": "6th March, 11.30PM-12.30PM and 1PM-3PM",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/tune.png?raw=true",
        "type": "Lit",
        "registration_link": ""
    },
    {
        "title": "Quiz3",
        "days": ["2"],
        "tagline": "Welcome to Knowledgeville",
        "desc": "Tired of annoying online zoom quizzes? Missed the thrill of quizzing the way it was always meant to be, that is, in person ?\nHow would you like not 1 or 2, but a collection of 7 exciting quizzes?\nLSD Quizsoc presents, Askerville Manor, a week-long quiz fest with a wide variety of topics",
        "link": "https://docs.google.com/document/d/1-3Er3fIsE2weMjK7gHgZqn40-EOAlWkEggHgHcD4TuU/edit?usp=sharing",
        "location": "Main Seminar Hall",
        "date_time": "4th March 2022, 12PM-1PM and 3PM-5PM",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/tune.png?raw=true",
        "type": "Lit",
        "registration_link": ""
    },
    {
        "title": "Quiz4",
        "days": ["3"],
        "tagline": "Trivia Teleportation",
        "desc": "Tired of annoying online zoom quizzes? Missed the thrill of quizzing the way it was always meant to be, that is, in person ?\nHow would you like not 1 or 2, but a collection of 7 exciting quizzes?\nLSD Quizsoc presents, Askerville Manor, a week-long quiz fest with a wide variety of topics",
        "link": "https://docs.google.com/document/d/1-3Er3fIsE2weMjK7gHgZqn40-EOAlWkEggHgHcD4TuU/edit?usp=sharing",
        "location": "Main Seminar Hall",
        "date_time": "5th March 2022, 11AM-12PM and 2PM-4PM",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/tune.png?raw=true",
        "type": "Lit",
        "registration_link": ""
    },



    {
        "title": "Comedy Night",
        "days": ["1"],
        "tagline": "Karunesh Talwar",
        "desc": "Mumbai based stand-up comedian Karnunesh Talwar started out as script writer for the massively popular AIB Comedy Group.<br/><br/>Equipped with observational skills sharp as a blade and language skills of a scholar, his commentary on societal idiosyncrasies, with has garnered him a massive following on YouTube with over 700k followers.<br/><br/>We promise you a riot of a night with gut busting laughter and comedy which will set the stage for the whole fest experience at IIITA!",
        "location": "SJA IIITA",
        "date_time": "10.00 PM",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/tune.png?raw=true",
        "type": "Pro_Show",
        "registration_link": ""
    },
    {
        "title": "Party Night",
        "days": ["2"],
        "tagline": "The Pineapple Express, The Nonviolinist",
        "desc": "Effervescence '22 brings to you the concert of a life time with Banglore-based fusion band Pineapple Express! Pineapple Express brings life to the crowd with their progressive fusion take on Carnatic, Rock and Experimental Electronic music. From their debut in 2016, Pineapple Express has shot to fame after their hit single 'Money' on Kappa TV, and now it's time they bring their swagger to Effervescence '22!",
        "location": "IIITA Main Ground",
        "date_time": "8PM onwards",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/tune.png?raw=true",
        "type": "Pro_Show",
        "registration_link": "",
    },
    {
        "title": "Masti Night",
        "days": ["4"],
        "tagline": "Benny Dayal, Lohar the Blacksmiths",
        "desc": "Effervescence '22 brings to you the concert of a life time with one of India's top playback singers, Benny Dayal! He is a prominent singer in Hindi, Tamil, Telugu, Malayalam, Kannada, Gujarati and more. Benny Dayal rose to fame in 2009 with his hit song 'Rehna Tu' from the bollywood movie 'Delhi 6', and now it's time he brings his swagger to Effervescence '22!<br/><br/>The 6 piece band - Lohar The Blacksmiths was formed by friends Aritra, Sumukh, Vikas and Rakshith in 2019. Their band focused on covering Indian Classical and Multilingual Rock Music. Their music has won them several Battles of Bands and they have performed over 50 live concerts. Eventually, they were joined by Anoop and Sanath who make the current lineup for this up and coming indie rock band. Now they are performing on Day 3 at the Effe Pronites! The hype is absolutely on!",
        "location": "IIITA Main Ground",
        "date_time": "8PM onwards",
        "image": "https://github.com/Manas2403/efffe-images/blob/master/events/tune.png?raw=true",
        "type": "Pro_Show",
        "registration_link": ""
    },
]
